site_name: 咸不可闻的笔记本
site_url: https://xbkw.github.io/NoteBook/
repo_name: XBKW/NoteBook
repo_url: https://github.com/XBKW/NoteBook
edit_uri: tree/master/docs
site_description: 咸不可闻（XBKW）的笔记本

theme:
  name: material
  language: zh
  #custom_dir: overrides
  favicon:
  icon:
    logo: material/Wallet-outline
    repo: fontawesome/brands/github

  palette:

      # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: grey
      accent: brown
      toggle:
        icon: material/weather-sunset-down
        name: Switch to light mode
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: grey
      accent: brown
      scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Light mode
      # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: brown
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode

  font:
    text: LXGW WenKai Screen GB Screen # Share Tech
    code: JetBrains Mono
  features:
    - content.code.annotate
    - content.code.copy # 代码块一键复制
    # - navigation.instant # 点击内部链接时，不用全部刷新页面
    - navigation.instant.prefetch # 即时预取，当用户将鼠标悬停在链接上时，它将开始获取页面。
    - navigation.instant.progress # 进度指示器
    - navigation.tracking # 在url中使用标题定位锚点
    - navigation.tabs # 顶部显示导航顶层nav（也就是第一个节点）
    # - navigation.tabs.sticky # 滚动不隐藏顶部nav，需要配合navigation.tabs使用
    # #- navigation.sections # nav节点缩进
    - navigation.prune
    - navigation.path #导航路径痕迹导航
    - navigation.footer #页脚可以包含指向当前页面的上一页和下一页的链接
    # #- navigation.expand # 不折叠左侧nav节点
    - navigation.indexes # 指定节点index pages ，跟instant不兼容
    - navigation.top # 一键回顶部
    - search.suggest   # 搜索输入一些字母时推荐补全整个单词
    - search.highlight   # 搜索出的文章关键词加入高亮

nav:
  - 主页:
    - index.md

  - 文献阅读:
    - paper/index.md

  - 老饕食记:
    - taster/index.md
    - 吃在北交: 
      - coming.md

  - 待办:
    - todo.md
  

copyright: Copyright &copy; 2025 XBKW

extra:
  generator: true  #删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/XBKW
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/176742470?spm_id_from=333.1007.0.0
    - icon: fontawesome/solid/paper-plane
      link: mailto:<1209124158@qq.com> #联系方式
#    feedback:
#      title: 此页面有帮助吗？
#      ratings:
#        - icon: material/thumb-up-outline
#          name: This page was helpful
#          data: 1
#          note: >-
#            谢谢你的反馈！
#        - icon: material/thumb-down-outline
#          name: This page could be improved
#          data: 0
#          note: >-
#            Thanks for your feedback! Help us improve this page by
#            using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.

plugins:
  # - glightbox
  - search
  - offline


markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "\ue157"

